-- All Records --
SELECT *
FROM ONLINE_CHESS_GAMES;

-- Total games
SELECT COUNT(DISTINCT GAME_ID)
FROM ONLINE_CHESS_GAMES

 -- Total number of games won by white --
SELECT COUNT(DISTINCT GAME_ID)
FROM ONLINE_CHESS_GAMES
WHERE LOWER(WINNER) = 'white'

 --White Win Percentage
	SELECT ROUND((COUNT(B.GAME_ID)::decimal / COUNT(A.GAME_ID)::decimal) * 100,2) AS WHITE_WIN_PERCENTAGE
	FROM
		(SELECT *
			FROM ONLINE_CHESS_GAMES) A
	LEFT JOIN
		(SELECT *
			FROM ONLINE_CHESS_GAMES
			WHERE LOWER(WINNER) = 'white') B ON A.GAME_ID = B.GAME_ID
			
 --Draw Percentage
	SELECT ROUND((COUNT(B.GAME_ID)::decimal / COUNT(A.GAME_ID)::decimal) * 100,2) AS DRAW_PERCENTAGE
	FROM
		(SELECT *
			FROM ONLINE_CHESS_GAMES) A
	LEFT JOIN
		(SELECT *
			FROM ONLINE_CHESS_GAMES
			WHERE LOWER(WINNER) = 'draw') B ON A.GAME_ID = B.GAME_ID
			
--Famous move when black wins
SELECT OPENING_SHORTNAME,
	COUNT(OPENING_FULLNAME) AS CNT
FROM ONLINE_CHESS_GAMES
WHERE LOWER(WINNER) = 'black'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1

--Famous move when white wins
SELECT OPENING_SHORTNAME,
	COUNT(OPENING_FULLNAME) AS CNT
FROM ONLINE_CHESS_GAMES
WHERE LOWER(WINNER) = 'white'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1

 --High Rated Percentage
SELECT ROUND(100 * (COUNT(A1.*)::decimal / COUNT(B1.*)::decimal),2)
FROM
	(SELECT *
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'white'
			AND WHITE_RATING > BLACK_RATING
		UNION SELECT *
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'black'
			AND WHITE_RATING < BLACK_RATING) A1
RIGHT JOIN
	(SELECT *
		FROM ONLINE_CHESS_GAMES) B1 ON A1.GAME_ID = B1.GAME_ID

--High Rated& white win percentage when 
SELECT ROUND(100 * (COUNT(A1.*)::decimal / COUNT(B1.*)::decimal),2)
FROM
	(SELECT *
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'white'
			AND WHITE_RATING > BLACK_RATING) A1
RIGHT JOIN
	(SELECT *
		FROM ONLINE_CHESS_GAMES) B1 ON A1.GAME_ID = B1.GAME_ID

--High Rated& black win percentage when 
SELECT ROUND(100 * (COUNT(A1.*)::decimal / COUNT(B1.*)::decimal),2)
FROM
	(SELECT *
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'black'
			AND WHITE_RATING < BLACK_RATING) A1
RIGHT JOIN
	(SELECT *
		FROM ONLINE_CHESS_GAMES) B1 ON A1.GAME_ID = B1.GAME_ID

-- Max games won by
SELECT ID,
	COUNT(ID)
FROM
	(SELECT RATED,
			WHITE_ID AS ID
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'white'
		UNION ALL SELECT RATED,
			BLACK_ID AS ID
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'black') A
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1

-- Max games won -higher rating
SELECT ID,
	RATED,
	COUNT(ID)
FROM
	(SELECT RATED,
			WHITE_ID AS ID
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'white'
		UNION ALL SELECT RATED,
			BLACK_ID AS ID
		FROM ONLINE_CHESS_GAMES
		WHERE LOWER(WINNER) = 'black') A
WHERE ID = 'taranga'
GROUP BY 1,2